services:
  - type: web
    name: linkedin-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: MAX_PROFILES
        value: 200
      - key: OUTPUT_FILENAME
        value: /tmp/profiles.json
